apps:
  - name: cristianonunes-bk
    script: ./index.js
    watch: false
    exec_mode: cluster
    instances: 2
    max_memory_restart: '200M'

    name: cristianonunes-bd
    script: ./index.js
    watch: false
    exec_mode: cluster
    instances: 2
    max_memory_restart: '200M'